[phases.setup]
nixPkgs = ["python311", "deno", "cloudflare-warp", "curl", "ffmpeg"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "/opt/venv/bin/python get-pip.py",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x start.sh"
]