[phases.setup]
nixPkgs = ["python311", "curl", "ffmpeg", "cloudflare-warp"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install requests lxml flask gunicorn yt-dlp",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp",
  "chmod +x yt-dlp"
]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "bash start.sh"